Added base for database module
codex-team/task-manager pull request #10
Opened 2021-11-10 17:27 UTC by slaveeks

2021-11-10 17:39 UTC, n0str submitted a review, later dismissed

2021-11-10 17:39 UTC, n0str commented on database/index.ts
> +mongoose.connect("mongodb://localhost:27017/task-manager", {})
Надо взять этот URI из переменной окружения (env)

2021-11-10 17:39 UTC, n0str commented on database/interfaces/interfaces.ts
> +export interface Role extends mongoose.Document{
может быть комменты добавить к каждой роли

2021-11-10 17:39 UTC, n0str commented on database/models/models.ts
> +import mongoose from "..";
это норм? что-то я такого не видел никогда

2021-11-10 17:55 UTC, neSpecc requested changes

2021-11-10 17:55 UTC, neSpecc commented on database/index.ts
> +import * as mongoose from "mongoose";
весь код приложения надо положить в папку /src

2021-11-10 17:55 UTC, neSpecc commented on database/interfaces/interfaces.ts
> +    name: String,
все интерфейсы и свойства надо продокументировать

2021-11-10 17:55 UTC, neSpecc commented on database/interfaces/interfaces.ts
> +    role_id: mongoose.Schema.Types.ObjectId
мы используем camelCase

2021-11-11 09:51 UTC, n0str commented on src/config/config.ts
> +    public static dbUrl: string = process.env.DB_URL || '';
По умолчанию вместо пустоты лучше использовать что-нибудь вроде localhost:27017

2021-11-11 17:52 UTC, talyguryn requested changes

2021-11-15 16:11 UTC, talyguryn requested changes

2021-11-15 16:11 UTC, talyguryn commented on src/config/config.ts
> +dotenv.config();
```suggestion
```

2021-11-15 16:11 UTC, talyguryn commented on src/config/config.ts
> +dotenv.config({ path: path.join(__dirname, '/../../.env') });
```suggestion

dotenv.config({ path: path.join(__dirname, '/../../.env') });
```

2021-11-15 16:11 UTC, talyguryn commented on src/config/config.ts
> +dotenv.config();
the second call? no need

2021-11-15 16:11 UTC, talyguryn commented on src/database/index.ts
> +import mongoose from 'mongoose';
does it work?

2021-11-15 18:07 UTC, neSpecc requested changes

2021-11-15 18:07 UTC, neSpecc commented on src/database/interfaces/status.ts
> + * Interface for status
description is not clear

2021-11-15 18:12 UTC, khaydarov reviewed
Зачем в названиях интерфейсов префикс I*? не лучше ли сразу назвать User вместо IUser? Так код лучше воспринимается потому что в реальном мире (в предметной области) зависишь от User, а не I{Model}.

2021-11-15 18:12 UTC, khaydarov commented on src/database/models/subtask.ts
> +  parenId: {
```suggestion
  parentId: {
```

2021-11-15 18:12 UTC, khaydarov commented on src/database/models/project.ts
> +  name:{
```suggestion
  name: {
```

2021-11-16 14:07 UTC, neSpecc requested changes

2021-11-16 14:07 UTC, neSpecc commented on src/database/interfaces/project.ts
> +  /**
where is the `id`?

2021-11-16 14:07 UTC, neSpecc commented on src/database/interfaces/project.ts
> +  /**
and `dateCreated`

2021-11-16 14:07 UTC, neSpecc commented on src/database/interfaces/role.ts
> + * Interface for user's role
please describe what the `Role` is

2021-11-16 14:07 UTC, neSpecc commented on src/database/interfaces/status.ts
> + * Interface for task's status
please describe what the `status` is

2021-11-16 14:07 UTC, neSpecc commented on src/database/interfaces/status.ts
> +  /**
id?

2021-11-16 14:07 UTC, neSpecc commented on src/database/interfaces/task.ts
> +  name: string,
Task is not a human, it has 'title' not a 'name'

2021-11-16 14:07 UTC, neSpecc commented on src/database/interfaces/user.ts
> +  /**
id?

2021-11-16 18:06 UTC, neSpecc requested changes

2021-11-16 18:06 UTC, neSpecc commented on src/database/interfaces/task.ts
> +}
dateCreated

2021-11-16 18:06 UTC, neSpecc commented on src/database/interfaces/user.ts
> +interface User{
у нас же не будет авторизации. Не понимаю, что значит User

2021-11-18 11:18 UTC, neSpecc reviewed
оставил пару комментов. И еще вопрос, зачем удалилися yarn.lock?

2021-11-18 11:18 UTC, neSpecc commented on src/database/interfaces/teammate.ts
> +  type: string,
тут можно сразу Enum сделать

2021-11-18 11:18 UTC, neSpecc commented on src/database/models/status.ts
> +    ref: 'Project',
это название коллекции? тогда должно быть `projects`

2021-11-18 12:08 UTC, slaveeks commented on src/database/models/status.ts
> +    ref: 'Project',
Могу ошибаться, но вроде должно использоваться название модели

2021-11-18 13:54 UTC, neSpecc commented on src/database/models/status.ts
> +    ref: 'Project',
ок

2021-11-18 14:08 UTC, talyguryn approved these changes

2021-11-18 15:14 UTC, neSpecc requested changes

2021-11-18 15:14 UTC, neSpecc commented on src/database/interfaces/teammate.ts
> +  userName?: string,
лучше назвать `value`, тк это не имя пользователя. Например при type = email это будет адрес

2021-11-18 15:49 UTC, neSpecc commented on src/database/interfaces/teammate.ts
> +  value?: string,
а почему не обязательное поле?

2021-11-18 15:55 UTC, slaveeks commented on src/database/interfaces/teammate.ts
> +  value?: string,
Не знаю, честно) Показалось, что нужно

2021-11-18 15:56 UTC, neSpecc commented on src/database/interfaces/teammate.ts
> +  value?: string,
приведи кейс плз

2021-11-18 16:01 UTC, slaveeks commented on src/database/interfaces/teammate.ts
> +  value?: string,
Я понял, это довольно бесполезно

2021-11-18 16:06 UTC, neSpecc approved these changes

2021-11-18 18:04 UTC, merged