Added opportunity to edit task content
codex-team/task-manager pull request #103
Opened 2022-01-26 18:06 UTC by slaveeks

resolves #80

2022-01-28 11:29 UTC, TatianaFomina commented on app/frontend/src/components/views/project-view/components/TaskContent.tsx
> +    editor.save().then(res => {
i suggest using `async/await` syntax instead of `.then`

2022-01-28 11:29 UTC, TatianaFomina commented on app/frontend/src/components/views/project-view/components/TaskContent.tsx
> +  id: string;
please add some comments

2022-01-28 17:04 UTC, talyguryn commented
no "saved" notifies. need to discuss it but i want to see any marker to be sure that content was saved. may be sign "saved" or any loader, i don't know yet

2022-01-28 17:09 UTC, talyguryn commented
may i ask to change cursor to `pointer` when it moves to the dark area around the popup to click to close it?

2022-01-28 17:10 UTC, talyguryn commented
is this warning ok?

![image](https://user-images.githubusercontent.com/15259299/151591054-4992a874-170a-4caa-a56e-03e7f2b209c4.png)

2022-01-28 17:12 UTC, talyguryn commented
when i update task content in popup and close it that card does not update. it is not good too

2022-01-31 14:05 UTC, talyguryn commented
> Added page reload, when popup closes

that is not the best solution. can we just update title in the tasks list and ask react to update the layout of that card automatically?

2022-01-31 14:09 UTC, talyguryn commented
still see no marker for "saved success" state. is there any way to create it and implement?

need just to show a note "Saved" with opacity 50% somewhere for a 300ms

2022-01-31 14:10 UTC, talyguryn commented
strange position of the right column below X, which should not affect popup content. it is good? 

![image](https://user-images.githubusercontent.com/15259299/151808335-be1adf9b-6d25-4d72-afdf-db3c610ef7cb.png)

2022-01-31 14:17 UTC, TatianaFomina commented
> > Added page reload, when popup closes
> 
> that is not the best solution. can we just update title in the tasks list and ask react to update the layout of that card automatically?

@slaveeks @talyguryn 
in https://github.com/codex-team/task-manager/pull/104 added updating tasks data in list on status change (store is used for that purpose). Maybe we should consider merging mentioned pr first and then use the same approach here

2022-02-01 16:00 UTC, gohabereg requested changes

2022-02-01 16:00 UTC, gohabereg commented on app/frontend/src/components/views/project-view/components/TaskPopup.tsx
> +    return navigate(0);
navigate(0)?

2022-02-04 11:29 UTC, neSpecc requested changes

2022-02-04 11:29 UTC, neSpecc commented on app/frontend/src/tools.ts
> +export const EDITOR_JS_COMPONENT = 'editorjs';
name is not clear

2022-02-04 11:29 UTC, neSpecc commented on app/frontend/src/components/UI/editor/EditorJSComponent.tsx
> +      holder: 'editorjs',
hardcoded

2022-02-04 11:29 UTC, neSpecc commented on app/frontend/src/components/views/project-view/components/TaskContent.tsx
> +  const changeTask = async (editor: EditorJS): Promise<void> => {
jsdoc missed

2022-02-04 11:29 UTC, neSpecc commented on app/frontend/src/components/views/project-view/components/TaskContent.tsx
> +  const [isShow, setIsShow] = useState<boolean>(false);
>isShow

name is not clear

2022-02-04 11:29 UTC, neSpecc commented on app/frontend/src/components/views/project-view/components/TaskContent.tsx
> +    const block = JSON.stringify(res);
why `block`?

2022-02-04 11:29 UTC, neSpecc commented on app/frontend/src/components/views/project-view/components/TaskContent.tsx
> +      const result = await updateTask({ _id: id,
```suggestion
      const result = await updateTask({
         _id: id,
```

2022-02-04 11:29 UTC, neSpecc commented on app/frontend/src/components/views/project-view/components/TaskContent.tsx
> +        text: block });
```suggestion
        text: block 
      });
```

2022-02-04 11:29 UTC, neSpecc commented on app/frontend/src/components/views/project-view/components/TaskContent.tsx
> +  const time = 5000;
name is not clear

2022-02-04 11:29 UTC, neSpecc commented on app/frontend/src/components/views/project-view/components/TaskContent.tsx
> +        <EditorJSComponent data={ data } onDataChange={ throttledChange }/> }
better use debounce instead of throttle

2022-02-04 11:29 UTC, neSpecc commented on app/frontend/src/components/views/project-view/components/TaskPopup.tsx
> +        <TaskContent data={ data } id={ task?._id }/>}
bad linebreaks

2022-02-04 14:54 UTC, talyguryn approved these changes
tested, ok

2022-02-04 15:23 UTC, neSpecc approved these changes

2022-02-04 16:46 UTC, gohabereg approved these changes

2022-02-04 17:55 UTC, merged