Added CRUD for teammate
codex-team/task-manager pull request #105
Opened 2022-01-29 14:58 UTC by Y-k-Y

### resolves #102 

- Added CRUD for teammate
- Added service for teammate on frontend
- All tests passed on Postman

2022-01-31 15:43 UTC, TatianaFomina approved these changes

2022-01-31 15:57 UTC, talyguryn requested changes

2022-01-31 15:57 UTC, talyguryn commented on app/types/entities/teammate.ts
> +  dateCreated: string;
do we really need `dateCreated`?

2022-02-01 04:59 UTC, Y-k-Y commented on app/types/entities/teammate.ts
> +  dateCreated: string;
I'll remove it.

2022-02-03 15:04 UTC, talyguryn approved these changes

2022-02-04 15:01 UTC, merged