Database methods
codex-team/task-manager pull request #17
Opened 2021-11-13 15:46 UTC by slaveeks

2021-11-13 23:17 UTC, n0str requested changes

2021-11-13 23:17 UTC, n0str commented on .gitignore
> +<<<<<<< HEAD
что-то тут не так. Ты не пофиксил мердж конфликт и закоммитил его

2021-11-13 23:17 UTC, n0str commented on src/config/config.ts
> +ddddddddddddd *
что это?

2021-11-19 17:18 UTC, talyguryn commented
please merge `main` to this branch

2021-11-23 17:09 UTC, talyguryn requested changes
и надо вернуть `frontend/yarn.lock` файл

2021-11-23 17:09 UTC, talyguryn commented on package.json
> +    "dotenv": "^10.0.0",
эти пакеты уже есть в deps. уточни, где именно они дожны быть и убери дубликаты

![image](https://user-images.githubusercontent.com/15259299/143071102-dd4e4e42-e7be-4b1a-be9c-7798e0bccf7f.png)

2021-11-24 12:03 UTC, talyguryn approved these changes

2021-11-24 16:55 UTC, talyguryn commented
no need

2021-11-24 16:55 UTC, closed without merging