Initialized storybook in frontend dir with out-of-the-box examples
codex-team/task-manager pull request #22
Opened 2021-11-19 10:49 UTC by VanjaRo

Closes #20

2021-11-19 12:48 UTC, neSpecc requested changes
1) Предлагаю файлы stories хранить рядом с файлами компонентов. Там же рядом в будущем могут появиться тесты, доки, типы и тд. Для каждого компонента создавать свою папку.

```
/src
  /components
    /ui
      /button
        button.tsx
        button.stories.tsx
        button.test.ts
      /input
        ... 
```

2) Лучше убрать все примеры, лишний мусор. Можно оставить какой-то минимальный с парой строк

2021-11-19 17:40 UTC, neSpecc approved these changes

2021-11-24 11:49 UTC, talyguryn approved these changes

2021-11-24 12:17 UTC, ilyamore88 requested changes

2021-11-24 12:17 UTC, ilyamore88 commented on frontend/package.json
> +    "web-vitals": "^1.0.1"
Необходимо убрать из Dev зависимостей лишнее

2021-11-24 17:48 UTC, ilyamore88 approved these changes

2021-11-24 17:49 UTC, merged