Added base for UI/Button component
codex-team/task-manager pull request #24
Opened 2021-11-23 10:50 UTC by slaveeks

2021-11-23 16:56 UTC, talyguryn commented on frontend/src/components/UI/button/Button.jsx
> +
а можно как-то сюда хотя бы лейбл для кнопки передать?

2021-11-24 13:49 UTC, ilyamore88 requested changes

2021-11-24 13:49 UTC, ilyamore88 commented on frontend/src/components/UI/button/Button.tsx
> +interface Props extends React.ButtonHTMLAttributes<HTMLButtonElement>{
Почему не HTMLProps? 
https://stackoverflow.com/questions/48198180/what-is-the-difference-between-react-htmlprops-and-react-htmlattributest

HTMLProps в том сиплее включают пропсы реакта.

2021-11-24 13:49 UTC, ilyamore88 commented on frontend/src/components/UI/button/Button.tsx
> +    </ButtonStyles>
Насколько я помню, нет смысла передавать props.children, так как ты это делаешь с помощью ...props

2021-11-24 15:50 UTC, ilyamore88 approved these changes

2021-11-24 15:51 UTC, talyguryn approved these changes

2021-11-24 15:52 UTC, merged