Project API methods added
codex-team/task-manager pull request #46
Opened 2021-11-30 12:39 UTC by castlesofplacebo

resolve #43

2021-11-30 13:03 UTC, talyguryn requested changes

2021-11-30 13:03 UTC, talyguryn commented on src/index.ts
> +server.post('/api/createProject', (_request, reply) => {
будет чуть логичнее разбивать роуты по шагам, чтобы чувствовать структуру. даже для временного кода.

не `/api/createProject`
а `/api/project/create`

ну и так далее 
`/api/project/delete`
`/api/project/find`
`/api/project/update`

2021-11-30 13:03 UTC, talyguryn commented on src/database/test_usage.ts
> +// Usage:
давай даже такие тесты писать через cypress

2021-12-01 16:15 UTC, talyguryn commented on app/backend/.env.sample
> +DB_URL=mongo://mongo:27017/task-manager
это же название протокола, по которому нужно общаться с монгой. надо вернуть как было.

```suggestion
DB_URL=mongodb://mongo:27017/task-manager
```

2021-12-01 16:49 UTC, slaveeks commented on app/backend/src/database/interfaces/project.ts
> +  findById: (id : mongoose.Types.ObjectId) => Promise<ProjectDocument>
Вроде как этот метод нужно прописать в интерфейсе модели, так как тут только методы относящиеся к конкретной модели. А еще в монгосе, насколько я помню, уже есть метод findByid

2021-12-03 12:44 UTC, castlesofplacebo commented
Для реализации остались:
- метод получения всех проектов
- перенос методов из ctproto в отдельную директорию

2021-12-03 13:18 UTC, neSpecc requested changes

2021-12-03 13:18 UTC, neSpecc commented on app/backend/src/database/interfaces/project.ts
> +interface Project {
можно не дублировать, а сразу использовать интерфейс из types/entities

2021-12-03 13:18 UTC, neSpecc commented on app/backend/src/ui/ctproto.ts
> +        const newProject = await Project.create({
бизнес-логику нужно отделить от ui

2021-12-03 13:18 UTC, neSpecc commented on app/types/transport/index.ts
> +import GetProjectsResponse from "./responses/project/get-projects";
eslint fix

2021-12-03 13:18 UTC, neSpecc commented on app/types/transport/requests/project/create.ts
> +export default interface CreateProject extends NewMessage<CreateProjectPayload> {
```suggestion
export default interface CreateProjectMessage extends NewMessage<CreateProjectPayload> {
```

2021-12-03 13:18 UTC, neSpecc commented on app/types/transport/requests/project/create.ts
> +  title: string;
не описаны свойства и интерфейс

2021-12-04 12:58 UTC, castlesofplacebo commented on app/backend/src/database/interfaces/project.ts
> +interface Project {
кажется эти интерфейсы нужны для моделей mongoose

2021-12-04 13:08 UTC, neSpecc commented on app/backend/src/database/interfaces/project.ts
> +interface Project {
ну да, просто импортируй из entities и передай в mongoose

2021-12-05 12:36 UTC, khaydarov commented on app/backend/src/ui/ctproto.ts
> +      if (message.type === 'create-project') {
Как планируешь расширять onMessage?
Между UI (Transport) должен быть слой, работающий с бизнес-логикой приложения. Называют UseCase или Application Service. Если вынесешь обработку `message.type`, то у тебя появится возможность выполнять код приложения из другого транспорта. 

Можно пока по простому, например
```js
class CreateProject implements UseCase {
      public get type(): string {
           return 'create-project';
      }

      public handle(payload) {
           // логика создания
      }
}
```

а выше нужно инициализировать эти классы:
```js
const useCases = [
    new CreateProject(....dependencies),
    new SomeOtherUseCase(...dependencies),
   ...
]
```

2021-12-05 12:38 UTC, khaydarov commented on app/backend/src/ui/ctproto.ts
> +      if (message.type === 'create-project') {
И соответственно когда получил сообщение по веб-сокету, надо найти нужный класс и передать `message.payload` в метод `handle`

2021-12-07 17:54 UTC, neSpecc approved these changes

2021-12-08 09:26 UTC, talyguryn approved these changes

2021-12-08 12:46 UTC, merged