Added sidebar heading
codex-team/task-manager pull request #48
Opened 2021-12-01 14:59 UTC by slaveeks

2021-12-03 11:08 UTC, neSpecc requested changes

2021-12-03 11:08 UTC, neSpecc commented on app/frontend/src/components/UI/SidebarInput/SidebarInput.tsx
> +  width: 75%;
а почему ширина захардкожена?

2021-12-03 11:08 UTC, neSpecc commented on app/frontend/src/components/UI/SidebarInput/SidebarInput.tsx
> +    color: var(--color-text-dark);
при фокусе плейсхолдер становится темным? не совсем понял суть

2021-12-03 11:08 UTC, neSpecc commented on app/frontend/src/components/UI/SidebarTitle/SidebarTitle.tsx
> +  color: var(--color-text-dark);
основной цвет текста можно задать у всего приложения и не задавать у каждого элемента

2021-12-03 11:08 UTC, neSpecc commented on app/frontend/src/components/layouts/base/Sidebar.stories.tsx
> +      <Button size={Sizes.SMALL} styleType={StyleTypes.SECONDARY}/>
почему капсом? и еще, [енумы](https://www.typescriptlang.org/docs/handbook/enums.html) в ts пишутся в единственном числе 

и не очень понятно, почему тут Small (это кстати какие? у нас вроде пока один размер кнопок) и стиль secondary лучше наверное сделать Default

2021-12-03 11:08 UTC, neSpecc commented on app/frontend/src/components/layouts/base/Sidebar.stories.tsx
> +  children: 'Codex Tasks',
```suggestion
  children: 'CodeX Tasks',
```

2021-12-03 11:08 UTC, neSpecc commented on app/frontend/src/components/layouts/sidebar/SidebarSearch.tsx
> +const SidebarSearchStyled = styled.div<Props>`
тут должен использоваться универсальный компонент инпута.

2021-12-03 11:08 UTC, neSpecc commented on app/frontend/src/styles/Colors.ts
> +    --color-form-light: #8D8D8D
что такое color-form? цвет формы? если это цвет текста, то лучше написать --color-text-secondary

2021-12-03 15:08 UTC, slaveeks commented on app/frontend/src/components/UI/SidebarInput/SidebarInput.tsx
> +  width: 75%;
Вообще, я оставил место для иконки лупы

2021-12-03 15:09 UTC, slaveeks commented on app/frontend/src/components/UI/SidebarInput/SidebarInput.tsx
> +    color: var(--color-text-dark);
Может я немного не понял мысль дизайна, но я сделал так, что когда инпут активный placeholder и border становятся темными

2021-12-03 15:11 UTC, slaveeks commented on app/frontend/src/styles/Colors.ts
> +    --color-form-light: #8D8D8D
Вообще, это цвет рамки. В том смысле, как я сверху описал, про затемнение

2021-12-03 16:46 UTC, ilyamore88 commented on app/frontend/src/styles/Global.ts
> +    color: var(--color-text-dark);
Почему не у body?

2021-12-04 12:45 UTC, ilyamore88 approved these changes

2021-12-04 13:23 UTC, neSpecc approved these changes

2021-12-04 13:33 UTC, merged