Added architecture.md and wrote base info about architecture of task manager
codex-team/task-manager pull request #5
Opened 2021-10-26 20:20 UTC by slaveeks

Wrote the first ideas about architecture of task manager. 

resolves #2

2021-11-11 09:47 UTC, neSpecc requested changes

2021-11-11 09:47 UTC, neSpecc commented on docs/architecture.md
> ++ tasks - array of task_id from Task
таски бесконечны, хранить их в массиве в одном поле — не лучшее решение

2021-11-11 09:47 UTC, neSpecc commented on docs/architecture.md
> +Task contains executors, status and may contains subtasks
исполнитель это assignee

2021-11-11 09:47 UTC, neSpecc commented on docs/architecture.md
> ++ status - status_id from Status. Status can be "ToDo", "InProgress", "Done"
```suggestion
+ status - status_id from the "statuses" table. 
```

2021-11-11 09:47 UTC, neSpecc commented on docs/architecture.md
> ++ subTasks - array of subtask_id from Subtask. Any Task can have from 0 to infinity subtasks
вместо этого достаточно parentId

2021-11-24 17:43 UTC, talyguryn commented
no need

2021-11-24 17:43 UTC, closed without merging