Add project header component
codex-team/task-manager pull request #53
Opened 2021-12-01 21:49 UTC by TatianaFomina

2021-12-01 21:50 UTC, TatianaFomina commented on app/frontend/src/components/layouts/project/ProjectHeader.tsx
> +import Button from '../../UI/button/Button';
я не поняла, как алиасы настроить, чтобы не писать относительные пути

2021-12-01 21:51 UTC, TatianaFomina commented on app/frontend/src/styles/Global.ts
> +    font-family: 'SF Pro Display', sans-serif;
еще по поводу шрифта вопрос, это какой-то эппловский шрифт? его надо подключать?

2021-12-01 22:11 UTC, ilyamore88 requested changes

2021-12-01 22:11 UTC, ilyamore88 commented on app/frontend/src/components/layouts/project/ProjectHeader.tsx
> +const ProjectHeader: React.FC<Props> = ({ ...props }) => {
Если ты не вытягиваешь из объекта конкретные пропы, то можно вот так
```suggestion
const ProjectHeader: React.FC<Props> = (props) => {
```

2021-12-01 22:11 UTC, ilyamore88 commented on app/frontend/src/styles/Global.ts
> + * CSS color variables
Описание не соответствует переменной

2021-12-01 22:17 UTC, TatianaFomina commented on app/frontend/src/styles/Global.ts
> + * CSS color variables
поправила

2021-12-01 22:20 UTC, ilyamore88 approved these changes
👍

2021-12-02 07:33 UTC, neSpecc commented on app/frontend/src/styles/Global.ts
> +    font-family: 'SF Pro Display', sans-serif;
его не надо хардкодить и подключать, надо использовать [system fonts](https://css-tricks.com/snippets/css/system-font-stack/)

2021-12-02 07:33 UTC, neSpecc commented on app/frontend/src/components/layouts/project/ProjectHeader.tsx
> +const ProjectHeader: React.FC<Props> = (props) => {
вы уверены, что этот компонент надо привязывать к project? У настроек воркспейса, например, такой же header. а также у формы создания/редактирования проекта

2021-12-02 07:33 UTC, neSpecc commented on app/frontend/src/components/layouts/project/ProjectHeader.tsx
> +  projectTitle: string
не описано свойство

2021-12-02 07:36 UTC, TatianaFomina commented on app/frontend/src/components/layouts/project/ProjectHeader.tsx
> +const ProjectHeader: React.FC<Props> = (props) => {
можно компонент Title просто в отдельный файл вынести, переименовать в PageTitle

2021-12-02 07:45 UTC, neSpecc commented on app/frontend/src/components/layouts/project/ProjectHeader.tsx
> +const ProjectHeader: React.FC<Props> = (props) => {
можно попробовать

2021-12-02 07:58 UTC, neSpecc approved these changes

2021-12-02 08:11 UTC, talyguryn commented
я правильно понимаю, что этот реквест закрывает и #32 задачу?

2021-12-02 08:40 UTC, TatianaFomina commented
> я правильно понимаю, что этот реквест закрывает и #32 задачу?

не совсем, я только необходимые для данной таски стили добавила. Как минимум, цвета точно еще не все

2021-12-02 17:33 UTC, merged