Create .env file to define host and por
codex-team/task-manager pull request #56
Opened 2021-12-02 16:05 UTC by lehatheslayer

resolves #51

2021-12-06 12:49 UTC, neSpecc commented on app/backend/.env.sample
> +HOST='0.0.0.0'
добавь плз описание переменных. Сходу не понятно, чем отличается PORT от CTPROTO_PORT и тд

2021-12-09 15:15 UTC, ilyamore88 commented on app/backend/src/index.ts
> +  console.log(process.env.NODE_ENV);
Этот лог нам нужен?

2021-12-09 15:23 UTC, lehatheslayer commented on app/backend/src/index.ts
> +  console.log(process.env.NODE_ENV);
Нет, забыл убрать)

2021-12-09 15:30 UTC, ilyamore88 approved these changes

2021-12-15 18:57 UTC, talyguryn requested changes

2021-12-15 18:57 UTC, talyguryn commented on .github/workflows/build-and-push-docker-image.yml
> +          envkey_REACT_APP_ENDPOINT_BACKEND: 'http://localhost:3000'
```suggestion
          envkey_REACT_APP_ENDPOINT_BACKEND: 'https://team.codex.so'
```

2021-12-15 18:57 UTC, talyguryn commented on .github/workflows/build-and-push-docker-image.yml
> +          envkey_REACT_APP_ENDPOINT_CTPROTO: 'ws://localhost:3080'
```suggestion
          envkey_REACT_APP_ENDPOINT_CTPROTO: 'wss://team.codex.so'
```

2021-12-17 13:36 UTC, slaveeks approved these changes

2021-12-17 15:37 UTC, talyguryn requested changes

2021-12-17 15:37 UTC, talyguryn commented on .github/workflows/build-and-push-docker-image.yml
> +      - name: Make backend envfile
эти правки надо убрать. не нужно

2021-12-17 17:15 UTC, talyguryn approved these changes

2021-12-17 17:15 UTC, merged