Entity description added
codex-team/task-manager pull request #6
Opened 2021-10-26 21:58 UTC by castlesofplacebo

resolve #3 

Описаны базовые сущности: User, Task и Workspace. Предлагаемые сущности (такие как Label, Status, Priority и View) рассмотрены для улучшения читабельности и впоследствии могут быть включены в поля соответствующих классов.

2021-11-02 12:05 UTC, talyguryn commented
в итоге для реализации мвп предлагается отказаться от всех дополнительных отвлекающих сущностей и сделать хотя бы канбан доску. сущность "пользователь" тоже можно пока не проектировать. 

оставляем простейшую модель таски:

- заголовок
- описание

модель колонки:

- заголовок
- список карточек

и проекта:

- название
- список колонок

2021-11-02 12:06 UTC, talyguryn commented
позже займемся реализацией тегов

2021-11-17 08:52 UTC, neSpecc requested changes

2021-11-17 08:52 UTC, neSpecc commented on entities.md
> +`WorkspaceName`: String
лучше просто `name`, чтобы не было workspaceSettings.workspaceName

2021-11-17 08:52 UTC, neSpecc commented on entities.md
> +`Telegram`: Link
я бы убрал это в поле contacts:

```
contacts: [
  {
    type: 'telegram', // или enum number , типа 0 - Email, 1 — Telegram и тд 
    value: 'username' 
  },
  ...
]
```

2021-11-17 08:52 UTC, neSpecc commented on entities.md
> +`WorkspaceSettings`: Workspace Settings
есть смысл это заворачивать в отдельное поле? может сразу в workspace поместить `name` и `team`?

2021-11-17 08:52 UTC, neSpecc commented on entities.md
> +`ProjectSettings`: Project Settings
такой же вопрос, как и с воркспейсами

2021-11-17 08:52 UTC, neSpecc commented on entities.md
> +`Backlog`: List[Task]
этот список будет постоянно разрастаться, поэтому лучше не хранить таски в проекте, а вынести в отдельную коллекцию `Tasks`, и там у задач будет `projectId`. 

Вот хорошая статья на эту тему: https://www.mongodb.com/blog/post/6-rules-of-thumb-for-mongodb-schema-design-part-3

> Three: Arrays should not grow without bound. If there are more than a couple of hundred documents on the “many” side, don’t embed them;

> For “one-to-squillions”, you should use a “parent-reference” in the document storing the “N” side.

2021-11-17 08:52 UTC, neSpecc commented on entities.md
> +`CreateDate`: Date
```suggestion
`dateCreated`: Date
```

2021-11-17 08:52 UTC, neSpecc commented on entities.md
> +`ProjectName`: String
name

2021-11-17 08:52 UTC, neSpecc commented on entities.md
> +`Chat`: Link
messengerChannelUrl

2021-11-17 08:52 UTC, neSpecc commented on entities.md
> +`CreateDate`: Date
dateCreated

2021-11-17 08:52 UTC, neSpecc commented on entities.md
> +`Text`: JSON
title
text

2021-11-17 08:52 UTC, neSpecc commented on entities.md
> +`Parent_id`: Integer
parentId

2021-11-17 08:52 UTC, neSpecc commented on entities.md
> +*Create(Project)*
создания и удаления воркспейсов пока не будет. И почему туда передается проект?

2021-11-17 08:52 UTC, neSpecc commented on entities.md
> +*Delete()*
по идее тут будет все из CRUD

2021-11-17 08:52 UTC, neSpecc commented on entities.md
> +*SetReport()*
не понятно, что это

2021-11-17 08:52 UTC, neSpecc commented on entities.md
> +*CustomStatus*
не понятно, что это

2021-11-17 17:38 UTC, neSpecc commented on entities.md
> +`Projects`: List[Project]
```suggestion
`Projects`: List[ProjectId]
```

2021-11-17 17:38 UTC, neSpecc commented on entities.md
> +`Cotacts:` : [ { type: Contact Type,
```suggestion
`Cotacts`: [ { type: Contact Type,  
```

2021-11-17 17:38 UTC, neSpecc commented on entities.md
> +`Backlog`: Tasks
```suggestion
```

2021-11-17 17:38 UTC, neSpecc commented on entities.md
> +
projectId

2021-11-17 17:54 UTC, neSpecc commented on entities.md
> +`Assignee`: WorkspaceSettings:Team
teammateId

2021-11-18 11:41 UTC, neSpecc commented on entities.md
> +`Id`: Integer
все id будут string

2021-11-18 13:54 UTC, neSpecc approved these changes

2021-11-18 17:54 UTC, talyguryn approved these changes

2021-11-18 18:13 UTC, merged