Add input and image uploader components
codex-team/task-manager pull request #64
Opened 2021-12-04 22:57 UTC by TatianaFomina

2021-12-04 23:00 UTC, TatianaFomina commented on app/frontend/src/components/UI/image-uploader/ImageUploader.stories.tsx
> +  children: 'File uploader description', // Named slots ???
Я не смогла понять, есть ли в реакте что-нибудь вроде именнованных слотов, как во vue? А то тут очень просится что-то подобное

2021-12-04 23:01 UTC, TatianaFomina commented on app/frontend/src/components/UI/input/Input.stories.tsx
> +  children: 'Input description', // Named slots ???
и тут

2021-12-05 13:30 UTC, ilyamore88 requested changes
Я предлагаю вынести ImageUploader в отдельный компонент без Label и Description, чтобы можно было использовать компонент вот так без лишней логики:
<img width="169" alt="image" src="https://user-images.githubusercontent.com/37909603/144748216-a726d8eb-b920-42c8-be00-042dd942e35c.png">

Для Description и Label можно сделать отдельный компонент ImageUploaderForm:
<img width="479" alt="image" src="https://user-images.githubusercontent.com/37909603/144748238-f75c95e3-9ab6-44ca-9d11-bfcf2a28f2c6.png">

2021-12-05 13:30 UTC, ilyamore88 commented on app/frontend/src/components/UI/image-uploader/ImageUploader.tsx
> +  }
Почему не использовать props.previewUrl как дефолтное значение стейта вместо ''?

2021-12-05 13:30 UTC, ilyamore88 commented on app/frontend/src/react-app-env.d.ts
> -// / <reference types="react-scripts" />
Это можно удалять?

2021-12-05 13:30 UTC, ilyamore88 commented on app/frontend/src/components/UI/image-uploader/ImageUploader.stories.tsx
> +  children: 'File uploader description', // Named slots ???
Насколько я знаю, именованных слотов в React нет. Вообще, children в React это по иерархии наследники твоего элемента, это стоит понимать, когда ты используешь этот проп.
Тут надо просто выбрать, либо у тебя должен быть проп uploaderDescription, либо ты будешь использовать описание как `<Uploader>My Description</Uploader>`. Мне кажется, что вариант с children лучше для этого компонента.

2021-12-05 13:30 UTC, ilyamore88 commented on app/frontend/src/components/UI/image-uploader/ImageUploader.tsx
> +      { props.label && <LabelWrapper><label htmlFor="input">{props.label}</label></LabelWrapper> }
Этот htmlFor будет работать?

2021-12-05 13:30 UTC, ilyamore88 commented on app/frontend/src/components/UI/image-uploader/ImageUploader.tsx
> +      { props.label && <LabelWrapper><label htmlFor="input">{props.label}</label></LabelWrapper> }
Кроме того, учти, что аплоадеров может быть несколько на странице, следовательно, у тебя должен быть уникальный id. В React 18 [появится хук](https://github.com/reactwg/react-18/discussions/111) для такого, но пока мы на 17, тебе надо позаботиться об этом самой.

2021-12-05 13:30 UTC, ilyamore88 commented on app/frontend/src/components/UI/input/Input.tsx
> +        <label htmlFor="input">{props.label}</label>
Не уникальный id

2021-12-05 13:30 UTC, ilyamore88 commented on app/frontend/src/components/UI/input/Input.tsx
> +  };
Это обязательно выносить в отдельный компонент?

2021-12-05 13:30 UTC, ilyamore88 commented on app/frontend/src/components/UI/input/Input.tsx
> +      { props.children && <Description>{ props.children }</Description> }
А вот тут, как мне кажется, уже лучше использовать props.title, props.description. При этом, я бы всё это обернул в label, чтобы по клику на оба этих элемента появлялся курсор в Input.

2021-12-05 13:30 UTC, ilyamore88 commented on app/frontend/src/components/UI/input/Input.tsx
> +const Input: React.FC<Props> = (props) => {
Меня смущает в этом компоненте каша из элементов и `props.children as string`. Можно по аналогии сделать базовый Input без лейблов (он например пригодится в SearchInput), чтобы меньше логики было в компоненте. При этом, создать дополнительный компонент InputWithLabel, в который можно передавать title и description. К слову, можно запилить HOC withLabel, который будет оборачивать твои инпуты и добавлять туда Label. Такой HOC можно будет аналогично использовать для Select.

2021-12-05 13:34 UTC, TatianaFomina commented on app/frontend/src/components/UI/input/Input.tsx
> +const Input: React.FC<Props> = (props) => {
кто такой HOC?

2021-12-05 13:35 UTC, ilyamore88 commented on app/frontend/src/components/UI/input/Input.tsx
> +const Input: React.FC<Props> = (props) => {
https://reactjs.org/docs/higher-order-components.html

2021-12-05 13:35 UTC, TatianaFomina commented on app/frontend/src/react-app-env.d.ts
> -// / <reference types="react-scripts" />
не, это какая-то важная директива, ее надо оставить

2021-12-06 17:17 UTC, TatianaFomina commented on app/frontend/src/components/UI/input/Input.tsx
> +      { props.children && <Description>{ props.children }</Description> }
Если description через пропсы передавать, то не получится сделать вот такое

![image](https://user-images.githubusercontent.com/31101125/144891520-98dba14d-b1f6-4080-bd53-7e3f584a640e.png)

2021-12-06 17:18 UTC, TatianaFomina commented on app/frontend/src/components/UI/input/Input.tsx
> +const Input: React.FC<Props> = (props) => {
про InputWithLabel хорошая идея

2021-12-06 17:32 UTC, ilyamore88 commented on app/frontend/src/components/UI/input/Input.tsx
> +      { props.children && <Description>{ props.children }</Description> }
Скорее всего, для такого текста ты будешь использовать i18n. Там есть фича с тем, чтобы оборачивать текст в блоки. И тогда, у тебя там будет ссылка. Я не уверен на 100%, что это будет работать, только процентов на 90. Хотя твоё замечание тоже уместно. Давай тогда оставим Description через children.

2021-12-07 17:59 UTC, ilyamore88 requested changes
Если у нас есть LabeledInput, то его стоит оформить как отдельный компонент. В файле Input.tsx или LabeledInput.tsx

2021-12-07 17:59 UTC, ilyamore88 commented on app/frontend/src/components/UI/image-uploader-form/ImageUploaderForm.tsx
> +      <Wrapper label={ props.label } description={ props.children as string } hasValue={ hasUploadedFile }>
Мне не нравится это приведение типов. Тебе не нужны значения этих переменных. Может тогда сделать hasLabel, hasDescription и передать boolean?

2021-12-07 18:02 UTC, TatianaFomina commented on app/frontend/src/components/UI/image-uploader-form/ImageUploaderForm.tsx
> +      <Wrapper label={ props.label } description={ props.children as string } hasValue={ hasUploadedFile }>
да, можно

2021-12-07 18:03 UTC, TatianaFomina commented on app/frontend/src/components/UI/image-uploader-form/ImageUploaderForm.tsx
> +      <Wrapper label={ props.label } description={ props.children as string } hasValue={ hasUploadedFile }>
а по поводу LabeledInput - зачем тогда нужны higher order components, если их не использовать как обертку по необходимости и все равно создавать отдельный компонент в отдельном файле?

2021-12-07 18:08 UTC, ilyamore88 commented on app/frontend/src/components/UI/image-uploader-form/ImageUploaderForm.tsx
> +      <Wrapper label={ props.label } description={ props.children as string } hasValue={ hasUploadedFile }>
Тогда можно делать его в том же файле именованным экспортом. По дефолту возвращать обычный Инпут.

2021-12-07 18:09 UTC, ilyamore88 commented on app/frontend/src/components/UI/image-uploader-form/ImageUploaderForm.tsx
> +      <Wrapper label={ props.label } description={ props.children as string } hasValue={ hasUploadedFile }>
Мне просто смущает то, что в текущей реализации надо каждый раз делать labeled(Input). Хотя можно сделать const LabeledInput, export LabeledInput.

2021-12-07 18:10 UTC, ilyamore88 commented on app/frontend/src/components/UI/image-uploader-form/ImageUploaderForm.tsx
> +      <Wrapper label={ props.label } description={ props.children as string } hasValue={ hasUploadedFile }>
Да, можно было бы заменить labeled обычной обёрткой через props.children. Но с HOC кода всё равно меньше.

2021-12-07 18:21 UTC, TatianaFomina commented on app/frontend/src/components/UI/image-uploader-form/ImageUploaderForm.tsx
> +      <Wrapper label={ props.label } description={ props.children as string } hasValue={ hasUploadedFile }>
> Тогда можно делать его в том же файле именованным экспортом.
а где его стори хранить?

2021-12-07 18:31 UTC, ilyamore88 commented on app/frontend/src/components/UI/image-uploader-form/ImageUploaderForm.tsx
> +      <Wrapper label={ props.label } description={ props.children as string } hasValue={ hasUploadedFile }>
Я думаю, что в Input сделать Labeled раздел

2021-12-07 18:32 UTC, TatianaFomina commented on app/frontend/src/components/UI/image-uploader-form/ImageUploaderForm.tsx
> +      <Wrapper label={ props.label } description={ props.children as string } hasValue={ hasUploadedFile }>
а так же нельзя. в одной сторе только один компонент же можно использовать, не?

2021-12-09 17:13 UTC, ilyamore88 requested changes
Такое ощущение, будто плейсхолдер не по центру по вертикали
![image](https://user-images.githubusercontent.com/37909603/145443790-ce377c3e-4f26-48ea-8fb9-6147f8b532ac.png)

2021-12-09 17:19 UTC, TatianaFomina commented
> Такое ощущение, будто плейсхолдер не по центру по вертикали ![image](https://user-images.githubusercontent.com/37909603/145443790-ce377c3e-4f26-48ea-8fb9-6147f8b532ac.png)

Это дефолтное расположение плейсхолдера инпута, я ничего не меняла

2021-12-09 17:24 UTC, ilyamore88 requested changes

2021-12-09 17:24 UTC, ilyamore88 commented on app/frontend/src/components/UI/input/Input.tsx
> +    <InputWrapper >
```suggestion
    <InputWrapper>
```

2021-12-09 18:00 UTC, neSpecc commented on app/frontend/src/components/UI/image-uploader-form/ImageUploaderForm.tsx
> +  width: 309px;
hardcoded

2021-12-09 18:00 UTC, neSpecc commented on app/frontend/src/components/UI/image-uploader-form/ImageUploaderForm.tsx
> +  & > *:not(:last-child) {
можно вместо этого использовать класс?

2021-12-09 18:00 UTC, neSpecc commented on app/frontend/src/components/UI/image-uploader-form/ImageUploaderForm.tsx
> +const ImageUploaderForm: React.FC<Props> = (props) => {
у props надо указать тип

2021-12-09 18:00 UTC, neSpecc commented on app/frontend/src/components/UI/image-uploader/ImageUploader.tsx
> +export interface Props {
```suggestion
export interface ImageUploaderProps {
```

2021-12-09 18:00 UTC, neSpecc commented on app/frontend/src/components/UI/image-uploader/ImageUploader.tsx
> +export interface RefType {
название не понятное

2021-12-09 18:00 UTC, neSpecc commented on app/frontend/src/components/UI/input/Input.tsx
> +  width: 304px;
hardcoded?

2021-12-09 18:00 UTC, neSpecc commented on app/frontend/src/components/UI/input/Input.tsx
> +  width: 304px;
должна ширина всех инпутов быть одинаковой или зависеть от родителя?

2021-12-09 18:00 UTC, neSpecc commented on app/frontend/src/components/UI/labeled/Labeled.tsx
> +    letter-spacing: -0.005em;
может вынести font-size 14 и letter-spacing куда-то? через css `@apply` например

2021-12-09 18:00 UTC, neSpecc commented on app/frontend/src/styles/Colors.ts
> +    --color-gray-6: #1D2331;
это лишнее, тк это --color-contrast

2021-12-09 18:00 UTC, neSpecc commented on app/frontend/src/styles/Colors.ts
> +     --color-image-preview-border: var(--color-gray-4);
может просто --color-line? этот цвет не у всех серых линий?

2021-12-09 18:01 UTC, TatianaFomina commented on app/frontend/src/styles/Colors.ts
> +    --color-gray-6: #1D2331;
а как остальные назвать?

2021-12-09 18:03 UTC, TatianaFomina commented on app/frontend/src/styles/Colors.ts
> +     --color-image-preview-border: var(--color-gray-4);
не, например у карточки бордер #EBEBEB

2021-12-09 18:05 UTC, TatianaFomina commented on app/frontend/src/components/UI/image-uploader-form/ImageUploaderForm.tsx
> +  width: 309px;
сделать ширину инпута == 100% ширины родителя?

2021-12-09 18:14 UTC, neSpecc commented on app/frontend/src/components/UI/image-uploader-form/ImageUploaderForm.tsx
> +  width: 309px;
думаю да

2021-12-10 10:19 UTC, TatianaFomina commented on app/frontend/src/components/UI/labeled/Labeled.tsx
> +    letter-spacing: -0.005em;
для того, чтобы использовать @apply, нужен какой-то препроцессор?
https://caniuse.com/css-apply-rule

2021-12-10 16:08 UTC, TatianaFomina commented on app/frontend/src/styles/Colors.ts
> +    --color-gray-6: #1D2331;
ну я в итоге `--color-gray-6` переименовала в `--color-contrast`, остальные оставила как есть

2021-12-10 17:59 UTC, neSpecc commented on app/frontend/src/components/UI/labeled/Labeled.tsx
> +    letter-spacing: -0.005em;
обычно для этого postcss с плагином `postcss-apply` используется , но в styled-components есть свои [extending-styles](https://styled-components.com/docs/basics#extending-styles) — правда это кажется слегка для другого по смыслу. А еще можно вставлять миксины как переменные https://gist.github.com/carlosepp/7704cce24edba0520eb6b36d894f04ae

2021-12-10 18:03 UTC, neSpecc approved these changes

2021-12-10 18:51 UTC, TatianaFomina commented on app/frontend/src/components/UI/labeled/Labeled.tsx
> +    letter-spacing: -0.005em;
попыталась сделать `mixin` с настройками текста для компонентов, но выявилась проблема: абсолютные пути в импортах резолвятся только если они начинаются с директории `components`. Соответственно, путь до миксина, лежащего в `src/styles` выглядит так: `'components/../styles/Mixins'`, в противном случае вылезает ошибка при сборке. Такие пути оставлять не очень хочется, поэтому все-таки думаю стоит отложить миксины, и потом вместе с ними донастроить алиасы для импортов

2021-12-10 19:17 UTC, ilyamore88 approved these changes

2021-12-10 19:18 UTC, merged