Added card component
codex-team/task-manager pull request #67
Opened 2021-12-08 14:23 UTC by slaveeks

resolve #29

2021-12-08 15:30 UTC, ilyamore88 requested changes

2021-12-08 15:30 UTC, ilyamore88 commented on app/frontend/src/components/layouts/card/TaskInfo.tsx
> +const TaskInfo: React.FC<Props> = ({ ...props }) => {
```suggestion
const TaskInfo: React.FC<Props> = (props) => {
```

2021-12-08 15:30 UTC, ilyamore88 commented on app/frontend/src/components/layouts/card/TaskCompleteness.tsx
> +const TaskCompleteness: React.FC<Props> = ({ ...props }) => {
```suggestion
const TaskCompleteness: React.FC<Props> = (props) => {
```

2021-12-08 15:30 UTC, ilyamore88 commented on app/frontend/src/components/layouts/card/Card.tsx
> +const Card: React.FC<Props> = ({ ...props }) => {
```suggestion
const Card: React.FC<Props> = (props) => {
```

2021-12-08 15:30 UTC, ilyamore88 commented on app/frontend/src/components/layouts/card/Assignees.tsx
> +  }
Можно избавиться от if и двух return? Например, с помощью конструкции { boolean && return_value }

2021-12-08 15:34 UTC, ilyamore88 commented on app/frontend/src/components/layouts/card/Assignees.tsx
> +  }
И лучше перенести на новую строчку каждый элемент. В текущем формате нечитаемо

2021-12-08 15:50 UTC, slaveeks commented on app/frontend/src/components/layouts/card/Assignees.tsx
> +  }
Тут плюс прибавляется к числу, как вариант, можно так, мне кажется
<img width="634" alt="image" src="https://user-images.githubusercontent.com/81693471/145239205-d195397c-66cb-4b64-a581-38d892b377c0.png">

2021-12-08 15:54 UTC, ilyamore88 commented on app/frontend/src/components/layouts/card/Assignees.tsx
> +  }
`{ props.assigneesNumber && \`+${props.assigneesNumber}\`}`

2021-12-08 15:54 UTC, ilyamore88 commented on app/frontend/src/components/layouts/card/Assignees.tsx
> +  }
Хмм, что-то с markdown. { props.assigneesNumber && \`+${props.assigneesNumber}` }

2021-12-08 15:56 UTC, slaveeks commented on app/frontend/src/components/layouts/card/Assignees.tsx
> +  }
А, понял, спасибо, в TaskInfo, как понимаю, аналогично, без if и двух return?

2021-12-08 15:57 UTC, ilyamore88 commented on app/frontend/src/components/layouts/card/Assignees.tsx
> +  }
Ага, лучше стараться в функциональном компоненте иметь только один return, иначе сложнее понять, что в итоге отрисовывается

2021-12-08 16:41 UTC, ilyamore88 requested changes
- Проблема с выравниванием
- Проблема с отступами
- У карточки отсутсвует поведение hover, active

2021-12-09 11:42 UTC, ilyamore88 commented on app/frontend/src/components/UI/card/Card.tsx
> +      <Assignees assigneesNumber={props.assigneesNumber}/>
Если у меня 0 асайнов, то этот блок всё равно будет отображаться. + дизайн подразумевает, что при 1 асайне у меня не будет +1 под аватаркой, сейчас же у тебя отображается один пользователь и он же учитывается в подписи с +.

2021-12-09 11:48 UTC, neSpecc commented on app/frontend/src/components/UI/card/Card.tsx
> +    div :last-child{
не понятный и сложный селектор, лучше добавить класс к элементу

2021-12-09 11:48 UTC, neSpecc commented on app/frontend/src/components/UI/card/Card.tsx
> +    :last-child > :last-child {
и тут тоже

2021-12-09 11:48 UTC, neSpecc commented on app/frontend/src/components/UI/card/Card.tsx
> +  border-color: #F4F4F4;
цвет захардкожен

2021-12-09 11:48 UTC, neSpecc commented on app/frontend/src/components/UI/card/Card.tsx
> +      <Assignees assigneesNumber={props.assigneesNumber}/>
почему туда передается какое-то число, а не список пользователей?

2021-12-09 11:48 UTC, neSpecc commented on app/frontend/src/components/UI/card/TaskInfo.tsx
> +          {props.completedSubtasks} of {props.subtasksNumber} completed
может это сам компонент `TaskCompleteness` должен выводить? иначе в чем его смысл?. И лучше назвать `TaskProgress`, имхо, тк Completeness это полнота

2021-12-09 11:48 UTC, neSpecc commented on app/frontend/src/components/UI/card/Card.tsx
> +      <TaskInfo taskTitle={props.taskTitle} subtasksNumber={props.subtasksNumber} completedSubtasks={props.completedSubtasks}/>
а в чем суть отдельного компонента для task info? он где-то еще будет использоваться?

2021-12-09 15:27 UTC, neSpecc commented on app/frontend/src/styles/Colors.ts
> +    --color-card-border: #F4F4F4;
цвет лучше не привязывать к компоненту. Как вариант, `--color-line`

2021-12-09 16:19 UTC, neSpecc commented on app/frontend/src/components/UI/card/Card.tsx
> +  taskTitle: string;
свойства надо описать

2021-12-10 17:24 UTC, TatianaFomina commented on app/frontend/src/components/icons/DefaultAvatar.svg
> +<path d="M0 9C0 6.20435 0 4.80653 0.456723 3.7039C1.06569 2.23373 2.23373 1.06569 3.7039 0.456723C4.80653 0 6.20435 0 9 0C11.7956 0 13.1935 0 14.2961 0.456723C15.7663 1.06569 16.9343 2.23373 17.5433
> fill="#EBEBEB"

может не хардкодить цвет иконок?

2021-12-10 17:31 UTC, TatianaFomina commented
Если заголовок слишком длинный, то наверное имеет смысл его сокращать и уводить под многоточие

![image](https://user-images.githubusercontent.com/31101125/145616519-ec62d5e8-058c-49a6-8faa-d002e9e66de1.png)

2021-12-10 19:24 UTC, ilyamore88 requested changes

2021-12-10 19:24 UTC, ilyamore88 commented on app/frontend/src/components/UI/card/Card.tsx
> +  }
Почему это всё не через Styled Components?

2021-12-10 19:24 UTC, ilyamore88 commented on app/frontend/src/components/icons/DefaultAvatar.svg
> +<path d="M0 9C0 6.20435 0 4.80653 0.456723 3.7039C1.06569 2.23373 2.23373 1.06569 3.7039 0.456723C4.80653 0 6.20435 0 9 0C11.7956 0 13.1935 0 14.2961 0.456723C15.7663 1.06569 16.9343 2.23373 17.5433
Я не думаю, что сейчас это принципиально. Есть [тикет](#63) на создание компонента, в котором это можно предусмотреть.

2021-12-10 19:24 UTC, ilyamore88 commented on app/frontend/src/styles/Colors.ts
> +    */
```suggestion
     * Card component colors variables
     */
```

2021-12-13 12:14 UTC, neSpecc requested changes

2021-12-13 12:14 UTC, neSpecc commented on app/frontend/src/components/UI/card/Card.tsx
> +        { props.subtasksNumber?
```suggestion
        { props.subtasksNumber ?
```

2021-12-13 12:14 UTC, neSpecc commented on app/frontend/src/components/UI/card/Card.tsx
> +          </Progress> : null }
закрывающая скобка должна быть под открывающей

2021-12-13 12:14 UTC, neSpecc commented on app/frontend/src/components/UI/card/Card.tsx
> +          `+${props.assigneesNumber-1}`: null }
и тут

2021-12-13 12:14 UTC, neSpecc commented on app/frontend/src/styles/Colors.ts
> +    --color-line: #F4F4F4;
все эти цвета уже есть. И вообще, что-то у нас уже третья группа переменных описывает линии, можно использовать уже существующие?

2021-12-13 12:46 UTC, slaveeks commented on app/frontend/src/styles/Colors.ts
> +    --color-line: #F4F4F4;
Вообще можно, но они называются --color-input-border и тд

2021-12-13 13:51 UTC, neSpecc commented on app/frontend/src/styles/Colors.ts
> +    --color-line: #F4F4F4;
надо переименовать таким образом, чтобы не было привязки к компоненту или цвету. `--color-line` — нормальное название

2021-12-13 13:56 UTC, slaveeks commented on app/frontend/src/styles/Colors.ts
> +    --color-line: #F4F4F4;
Да, я думаю, это можно каким-нибудь следующим реквестом сделать, ибо color-input-border это от компонента формы, я использую color-line, могу пока только поменять присваивания цветов к этим переменным на уже прописанные оттенки

2021-12-13 14:00 UTC, slaveeks commented on app/frontend/src/styles/Colors.ts
> +    --color-line: #F4F4F4;
И убрать коммент, что это переменные цвета для карточки

2021-12-13 15:40 UTC, neSpecc commented on app/frontend/src/styles/Colors.ts
>       --color-input-border: var(--color-gray-2);
теперь эти переменные можно удалить, тк появились точно такие же, но более общие

2021-12-13 15:50 UTC, neSpecc approved these changes

2021-12-13 16:26 UTC, ilyamore88 approved these changes

2021-12-13 16:26 UTC, merged