Add project form
codex-team/task-manager pull request #72
Opened 2021-12-11 19:54 UTC by TatianaFomina

Добавила роут `projects/new`, по которому открывается форма создания проекта. Загруженную картинку решено было игнорировать, пока не будет реализована возможность отдельно ее куда-то загружать и сохранять в проект ее урл.

2021-12-14 16:40 UTC, talyguryn approved these changes

2021-12-16 09:12 UTC, ilyamore88 requested changes

2021-12-16 09:12 UTC, ilyamore88 commented on app/frontend/src/components/UI/input/Input.tsx
> +    ${ UiComponentText }
```suggestion
    ${ UiComponentText };
```

2021-12-16 09:12 UTC, ilyamore88 commented on app/frontend/src/components/UI/labeled/Labeled.tsx
> +  ${ UiComponentText }
```suggestion
  ${ UiComponentText };
```

2021-12-16 16:22 UTC, ilyamore88 approved these changes

2021-12-16 16:50 UTC, neSpecc commented on app/frontend/src/components/views/projects/ProjectForm.tsx
> +  & > *:not(:last-child) {
( ͡° ʖ̯ ͡°)

2021-12-16 16:50 UTC, neSpecc commented on app/frontend/src/components/views/projects/ProjectForm.tsx
> +  & > *:not(:last-child) {
можно же просто `${LabeledInput}` по идее?

2021-12-16 16:50 UTC, neSpecc commented on app/frontend/src/utils/ctproto-client/index.ts
> +import { CTProtoClient } from 'ctproto';
а почему это переехало в utils? это не похоже не утилиту

2021-12-16 16:50 UTC, neSpecc commented on app/frontend/src/styles/Mixins.ts
> +const UiComponentText = (): string => `
неплохо бы док написать (где это следует использовать)

2021-12-16 16:50 UTC, neSpecc commented on app/types/entities/project.ts
> +  id?: string;
почему это и дата стали опциональными? они же всегда есть у любого проекта

2021-12-16 17:24 UTC, TatianaFomina commented on app/frontend/src/utils/ctproto-client/index.ts
> +import { CTProtoClient } from 'ctproto';
оно просто в index.tsx было, нужно было куда-то переместить. Название директории выбрано полупроизвольно, готова обсудить другие варианты

2021-12-16 17:26 UTC, TatianaFomina commented on app/types/entities/project.ts
> +  id?: string;
при создании проекта на клиенте id и дата еще не существуют

https://github.com/codex-team/task-manager/pull/72/files#diff-d4e346330e78c44edbc74b423488e8d5d664daeb5e8f5f51f1fe8521b8c0489eR10

2021-12-16 17:28 UTC, neSpecc commented on app/frontend/src/utils/ctproto-client/index.ts
> +import { CTProtoClient } from 'ctproto';
можно было бы положить в папку `transport` или типа того, но еще надо будет подумать, как будет обработчик `onMessage` вызывать мутации стора

2021-12-16 17:51 UTC, TatianaFomina commented on app/frontend/src/components/views/projects/ProjectForm.tsx
> +  & > *:not(:last-child) {
кажется, так можно только styled components стилизовать

2021-12-16 17:54 UTC, TatianaFomina commented on app/frontend/src/components/views/projects/ProjectForm.tsx
> +  & > *:not(:last-child) {
ну то есть нельзя просто обычный реакт компонент туда передать

2021-12-16 18:05 UTC, neSpecc commented on app/types/entities/project.ts
> +  id?: string;
это другой объект по смыслу. Ты же создаешь проект на основе каких-то данных, а не на основе проекта.

то есть там будет что-то типа

```ts
type CreateProjectPayload = Omit<Project, 'id' | 'dateCreated'>
```

А еще лучше явно перечислить параметры, которые необходимы для создания проекта:

```ts
export async function createProject(title: string, picture?: string): Promise<CreateProjectResponsePayload> {
  const response = await client.send('create-project', {
    title,
    picture
  });

  if (response.errors){
    throw new CreateProjectError();
  }

  return response as CreateProjectResponsePayload;
}
```

2021-12-16 18:19 UTC, TatianaFomina commented on app/types/entities/project.ts
> +  id?: string;
поправила

2021-12-16 18:22 UTC, neSpecc commented on app/frontend/src/services/projects.ts
> +type CreateProjectPayload = Omit<Project, 'id' | 'dateCreated'>;
это сломается, как только в Project добавятся новые поля, а это точно произойдет. К тому же, типы данных в Проекте и в том, что отправляет клиент могут отличаться, лучше к этому не привязываться.

2021-12-17 12:59 UTC, neSpecc commented on app/frontend/src/services/projects.ts
> +  messengerChannelUrl: string
а это обязательное поле?

2021-12-17 13:01 UTC, neSpecc commented on app/frontend/src/components/views/projects/ProjectForm.tsx
> +  & > *:not(:last-child) {
давай попробует обернуть `LabeledInput` в `styled`

2021-12-17 15:36 UTC, TatianaFomina commented on app/frontend/src/services/projects.ts
> +  messengerChannelUrl: string
нет, поправила

2021-12-18 13:36 UTC, neSpecc approved these changes

2021-12-18 20:02 UTC, merged