Added project list
codex-team/task-manager pull request #73
Opened 2021-12-15 12:05 UTC by slaveeks

2021-12-15 13:15 UTC, talyguryn approved these changes

2021-12-15 17:51 UTC, neSpecc requested changes
No description provided.

2021-12-15 17:52 UTC, neSpecc commented
Картинка не ресайзится

<img width="1248" alt="image" src="https://user-images.githubusercontent.com/3684889/146239148-d2fba4d1-0956-4d44-b810-3820bcb17df1.png">

2021-12-16 09:15 UTC, ilyamore88 reviewed
Может убрать возможность выделять текст?
<img width="240" alt="image" src="https://user-images.githubusercontent.com/37909603/146342823-9526776a-1ce6-45e5-a956-0ac501c053f9.png">

2021-12-16 16:30 UTC, ilyamore88 approved these changes

2021-12-16 17:10 UTC, neSpecc commented on app/frontend/src/components/UI/project-list/components/ProjectListItem.tsx
> +  -webkit-user-select: none;
https://styled-components.com/docs/basics

> Automatic vendor prefixing: write your CSS to the current standard and let styled-components handle the rest.

2021-12-17 10:38 UTC, neSpecc commented on app/frontend/src/components/UI/project-list/components/ProjectListItem.stories.tsx
> +import { ComponentMeta, ComponentStory } from '@storybook/react';
а зачем внутри папки `components/UI/projects-list` еще одна папка components?

2021-12-17 10:38 UTC, neSpecc commented on app/frontend/src/components/UI/project-list/components/ProjectListItem.tsx
> +    background: var(--color-contrast);
при клике он мерцает контрастным фоном. Можно это отключить?

2021-12-17 10:41 UTC, slaveeks commented on app/frontend/src/components/UI/project-list/components/ProjectListItem.stories.tsx
> +import { ComponentMeta, ComponentStory } from '@storybook/react';
А куда тогда расположить элемент списка? Просто рядом с компонентом списка?

2021-12-17 10:42 UTC, slaveeks commented on app/frontend/src/components/UI/project-list/components/ProjectListItem.tsx
> +    background: var(--color-contrast);
Так вроде в дизайне, если я не ошибаюсь 
<img width="676" alt="image" src="https://user-images.githubusercontent.com/81693471/146532462-884de82b-08f6-47f6-892b-7362983a8f5c.png">

2021-12-17 11:14 UTC, neSpecc commented on app/frontend/src/components/UI/project-list/components/ProjectListItem.stories.tsx
> +import { ComponentMeta, ComponentStory } from '@storybook/react';
да

2021-12-17 11:15 UTC, neSpecc commented on app/frontend/src/components/UI/project-list/components/ProjectListItem.tsx
> +    background: var(--color-contrast);
это состояние выбранного пункта

2021-12-17 13:01 UTC, neSpecc approved these changes

2021-12-17 13:03 UTC, merged