Add project list view
codex-team/task-manager pull request #86
Opened 2021-12-24 16:15 UTC by TatianaFomina

- Добавлена возможность отображать задачи внутри проекта в виде списка
 - Добавлен инпут для создания новой задачи
 
 В текущей реализации отсутствуют:
 - отображение статуса задачи (и фильтра задач по статусам)
 - отображение названия проекта в заголовке страницы и в карточке задачи (нужно либо добавить метод для получения информации о проекте по id, либо придумать, как передавать эти данные при навигации из списка проектов)

2021-12-24 16:43 UTC, talyguryn approved these changes

2021-12-24 17:20 UTC, ilyamore88 commented on app/frontend/src/components/UI/input/Input.tsx
> +        onChange={ ({ target: { value } }) => props.onChange(value) }
Can you add line breaks pls?

2021-12-24 17:20 UTC, ilyamore88 commented on app/frontend/src/components/UI/task-input/TaskInput.tsx
> + * @param props
Fix eslint

2021-12-24 17:20 UTC, ilyamore88 commented on app/frontend/src/components/UI/task-input/TaskInput.tsx
> + * Component for creating nee tasks
```suggestion
 * Component for creating new tasks
```

2021-12-24 17:23 UTC, TatianaFomina commented on app/frontend/src/components/UI/input/Input.tsx
> +        onChange={ ({ target: { value } }) => props.onChange(value) }
`props.onChange(value)` перенести на новую строку?

2021-12-24 17:27 UTC, ilyamore88 commented on app/frontend/src/components/UI/input/Input.tsx
> +        onChange={ ({ target: { value } }) => props.onChange(value) }
MB something like 
```js
onChange={
  (event) => {
    props.onChange(event.target.value);
  }
}
```

It's easier to understand as for me)

2021-12-24 17:36 UTC, ilyamore88 reviewed
Storybook is broken

<img width="1077" alt="image" src="https://user-images.githubusercontent.com/37909603/147367238-e2110982-a655-435d-bc5c-4b3bc9a7f259.png">

2021-12-24 18:01 UTC, gohabereg requested changes

2021-12-24 18:01 UTC, gohabereg commented on app/frontend/src/components/UI/project-list/ProjectLink.tsx
> +const StyledLink = styled(Link)`
Общий коммент — лучше стилизованные компоненты объявлять под основным, чтобы при просмотре файла сначала шел основной, а потом уже стилизованные. Можно наверное позже для всего проекта порефакторить

2021-12-24 18:01 UTC, gohabereg commented on app/frontend/src/components/UI/input/Input.tsx
> +          (event) =>
Анонимную функцию стоит вынести в отдельную переменную

2021-12-24 18:13 UTC, TatianaFomina commented on app/frontend/src/components/UI/task-input/TaskInput.tsx
> +        onBlur={ () => setFocused(false) }
а почему лучше не использовать?

2021-12-24 18:50 UTC, gohabereg approved these changes

2021-12-24 18:50 UTC, gohabereg commented on app/frontend/src/components/views/project-view/ProjectView.tsx
> +        text: JSON.stringify(taskContent),
Вот тут тоже stringify лучше вынести в createTask, компонент не должен думать о том, как обрабатываются данные

2021-12-24 18:50 UTC, gohabereg commented on app/frontend/src/components/views/project-view/ProjectView.tsx
> +        text: JSON.stringify(taskContent),
Хотя с текущей архитектурой можно пока так оставить, главное не забыть поменять, когда появится стейт-менеджер и прослойка для мутаций

2021-12-25 11:34 UTC, ilyamore88 approved these changes

2021-12-25 19:16 UTC, merged