Added popup component
codex-team/task-manager pull request #87
Opened 2021-12-24 17:29 UTC by slaveeks

2021-12-24 17:44 UTC, neSpecc requested changes
No description provided.

2021-12-25 14:30 UTC, ilyamore88 approved these changes

2021-12-25 14:42 UTC, gohabereg requested changes

2021-12-25 14:42 UTC, gohabereg commented on app/frontend/src/components/layouts/popup/Popup.tsx
> +  }, [ props ]);
props это объект, который будет меняться каждый раз при ререндере, так что эта конструкция с коллбэком будет только вредить производительности.

2021-12-25 14:42 UTC, gohabereg commented on app/frontend/src/components/layouts/popup/Popup.tsx
> +      props.backDropClick();
Используйте деструктор для пропсов, пожалуйста

2021-12-25 14:42 UTC, gohabereg commented on app/frontend/src/components/layouts/popup/Popup.tsx
> +interface Props{
Надо прогнать eslint

2021-12-25 14:42 UTC, gohabereg commented on app/frontend/src/components/layouts/popup/Popup.tsx
> +      <div onClick={e => e.stopPropagation()}>
Стоит создать хелпер stopPropagation, думаю не раз пригодится

2021-12-25 14:42 UTC, gohabereg commented on app/frontend/src/components/layouts/popup/Popup.tsx
> +    document.body
Не стоит создавать портал на body, из-за этого могут поломаться уже замаунченные туда компоненты. Лучше создать отдельный элемент для портала

2021-12-25 14:42 UTC, gohabereg commented on app/frontend/src/components/layouts/popup/PopupWrapper.tsx
> +const PopupWrapper: React.FC<Props> = (props) => {
Деструктор пропсов плиз

2021-12-25 14:42 UTC, gohabereg commented on app/frontend/src/components/layouts/popup/Popup.tsx
> +const PopupStyled = styled.div`
Styled компоненты лучше переносить под основной, чтобы при открытии файла сразу было видно именно основной

2021-12-25 15:07 UTC, slaveeks commented on app/frontend/src/components/layouts/popup/Popup.tsx
> +  }, [ props ]);
А какая альтернатива тогда, или можно тогда просто backDropClick передать?

2021-12-25 15:19 UTC, gohabereg commented on app/frontend/src/components/layouts/popup/Popup.tsx
> +  }, [ props ]);
Да, нужно `props.backDropClick`
Но тогда в родительском компоненте нужно будет этот коллбэк тоже в useCallback оборачивать, иначе функция будет каждый раз новая.

В данном случае без useCallback в общем будет проще и в некотором роде производительнее, потому что useCallback занимает память

2021-12-25 16:03 UTC, gohabereg commented on app/frontend/src/components/layouts/popup/PopupWrapper.tsx
> +  const { children, backDropClick, isPopupVisible } = props;
Лучше сразу при объявлении
```
const Component = ({ children, backDropClick, isPopupVisible }) => {}
```

2021-12-25 16:03 UTC, gohabereg commented on app/frontend/src/components/layouts/popup/Popup.tsx
> +      <div onClick={ e => stopPropagation(e) }>
```suggestion
      <div onClick={stopPropagation}>
```

2021-12-25 16:16 UTC, gohabereg approved these changes

2021-12-27 10:36 UTC, neSpecc approved these changes

2021-12-27 10:49 UTC, merged