Feature/refactoring backend src
codex-team/task-manager pull request #88
Opened 2021-12-26 21:24 UTC by castlesofplacebo

1. Методы по работе с базой данных перенесены в `/src/db-methods`.
2. Добавлен `messageDispatcher` для обработки `message.type`. Также добавлены хэндлеры для вызова соответсвующих методов `/src/db-methods`.
3. Исправлены имена у некоторых методов, работающих с `ctproto`.

2021-12-27 11:02 UTC, castlesofplacebo commented
из вопросов осталось определение типа `payload` в интерфейсе `MessageHandler`.

2021-12-27 15:58 UTC, TatianaFomina commented on app/backend/src/ui/transport-server/messageDispatcher.ts
> +  for (const handler of handlers) {
А может `handlers` сделать мапой вместо массива? Тогда не надо будет по всем элементам проходиться, можно будет хэндлер по ключу достать

2021-12-27 15:58 UTC, TatianaFomina commented on app/backend/tsconfig.json
> +    // "strictBindCallApply": true,                      /* Check that the arguments for `bind`, `call`, and `apply` db-methods match the original function. */
это из-за переименования во всем проекте?

2021-12-27 17:37 UTC, castlesofplacebo commented on app/backend/tsconfig.json
> +    // "strictBindCallApply": true,                      /* Check that the arguments for `bind`, `call`, and `apply` db-methods match the original function. */
да, вернула назад как было

2021-12-27 20:31 UTC, castlesofplacebo commented on app/backend/src/ui/transport-server/messageDispatcher.ts
> +  for (const handler of handlers) {
поправила

2022-01-10 11:22 UTC, neSpecc requested changes

2022-01-10 11:22 UTC, neSpecc commented on app/backend/src/ui/transport-server/handlers/messageHandler.ts
> +export interface MessageHandler {
не хватает доков

2022-01-10 11:22 UTC, neSpecc commented on app/backend/src/ui/transport-server/handlers/project/create.ts
> + *
доки

2022-01-10 11:22 UTC, neSpecc commented on app/backend/src/ui/transport-server/handlers/project/create.ts
> +  /**
доков нет

2022-01-10 11:22 UTC, neSpecc commented on app/backend/src/ui/transport-server/handlers/project/create.ts
> +  public async handle(payload): Promise<ApiResponse['payload'] | void> {
не указан тип payload

2022-01-10 11:22 UTC, neSpecc commented on app/backend/src/ui/transport-server/handlers/project/create.ts
> +  public async handle(payload): Promise<ApiResponse['payload'] | void> {
а выходящий тип получится более точно указать?

2022-01-10 11:22 UTC, neSpecc commented on app/backend/src/ui/transport-server/messageDispatcher.ts
> +  }
давай в else добавим ответ `Unknown message type`, можно через какой-то `UnknownMessageHandler`, например

2022-01-10 11:22 UTC, neSpecc commented on app/types/transport/index.ts
> +export type ApiMessagePayload =
а зачем этот тип?

2022-02-02 15:38 UTC, talyguryn commented on app/backend/src/ui/transport-server/messageDispatcher.ts
> +  }
later. when ctproto will be able to fire sending error responses

2022-02-02 15:38 UTC, talyguryn approved these changes

2022-02-02 15:54 UTC, neSpecc commented
What is the difference between the `database` and `db-methods` directories?


<img width="358" alt="image" src="https://user-images.githubusercontent.com/3684889/152188853-8635e87d-2d1b-45e8-927f-6d9402937873.png">

2022-02-02 15:55 UTC, talyguryn commented
> What is the difference between the `database` and `db-methods` directories?
> 
> <img alt="image" width="358" src="https://user-images.githubusercontent.com/3684889/152188853-8635e87d-2d1b-45e8-927f-6d9402937873.png">

Database  — Used to create a [connection to database](./index.ts) and define [mongoose models](./models) of entities.
Database Methods — Implement wrapper methods to access database.

2022-02-02 15:56 UTC, neSpecc commented on app/backend/src/ui/transport-server/handlers/project/create.ts
> +export class CreateProject implements MessageHandler {
```suggestion
export class CreateProjectHandler implements MessageHandler {
```

2022-02-02 15:58 UTC, neSpecc commented
> Database — Used to create a connection to database and define mongoose models of entities. Database Methods — Implement wrapper methods to access database.

Do we need both of them? They looks similar.

And also they both have strange names.

2022-02-02 16:00 UTC, neSpecc commented
sorry, missclicked

2022-02-02 21:17 UTC, talyguryn commented
> Do we need both of them? They looks similar.

actually there is a deeper problem while architecture is not clean yet. had a meeting with @khaydarov and we decide to define `application` and `domain` layers to get the best results

2022-02-16 15:30 UTC, slaveeks approved these changes

2022-02-16 15:38 UTC, merged