index.ts added
codex-team/task-manager pull request #9
Opened 2021-11-09 15:06 UTC by castlesofplacebo

resolve #8

Добавлены базовые сущности: `index.ts`, `tsconfig.json` и `package.json`.
Также добавлен файл `docker-compose.yml`

2021-11-09 15:42 UTC, neSpecc submitted a review, later dismissed

2021-11-09 15:42 UTC, neSpecc commented on package.json
> +  "version": "1.0.0",
```suggestion
  "version": "0.0.0",
```

2021-11-09 15:42 UTC, neSpecc commented on package.json
> +  "author": "",
```suggestion
  "author": "CodeX",
```

2021-11-09 15:42 UTC, neSpecc commented on package.json
> +  "license": "ISC",
```suggestion
  "license": "Unlicensed
 ",
```

2021-11-09 15:42 UTC, neSpecc commented on index.ts
> +import express from 'express';
давай положим в /src/index.ts

2021-11-09 15:48 UTC, n0str requested changes

2021-11-09 15:48 UTC, n0str commented on docker-compose.yml
> +    command: bash -c "yarn && yarn dev"
лучше вынести в Dockerfile

2021-11-09 15:51 UTC, n0str requested changes

2021-11-09 15:51 UTC, n0str commented on docker-compose.yml
> +    working_dir: /usr/src/app
Не понадобится при Dockerfile

2021-11-09 15:51 UTC, n0str commented on docker-compose.yml
> +    links:
links - избыточная директива. По умолчанию хосты и так общаются друг с другом. Сейчас links используется только для добавления дополнительных алиасов

2021-11-09 15:51 UTC, n0str commented on docker-compose.yml
> +    image: mongo
нужно зафиксировать версию mongodb

2021-11-09 15:51 UTC, n0str commented on docker-compose.yml
> +      - '27017:27017'
я бы написал `'127.0.0.1:27017:27017'` с точки зрения безопасности.

2021-11-09 15:58 UTC, talyguryn commented on docker-compose.yml
> +    command: bash -c "yarn && yarn dev"
не лучше. каждый раз при обновлении списка зависимостей придётся пересобирать образ. в отдельный сценарий можно будет вынести версию для прода, а для разработки это лучшее решение

2021-11-09 16:04 UTC, talyguryn requested changes
и ещё надо удалить package-lock.json файл, потому что будем использовать yarn.lock

2021-11-09 16:04 UTC, talyguryn commented on docker-compose.yml
> +    - '.:/usr/src/app'
мне кажется или тут пара пробелов потерялась?

2021-11-09 16:04 UTC, talyguryn commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
эту команду можно пока убрать

2021-11-09 17:01 UTC, ilyamore88 commented on package.json
> +  "license": "ISC",
```suggestion
  "license": "Unlicensed",
```

2021-11-10 11:43 UTC, n0str commented on docker-compose.yml
> +    command: bash -c "yarn && yarn dev"
А что плохого в том, чтобы обновлять образ при изменении зависимостей? Для этого докер все кеширует.
Зато вижу проблемы с кустарным компоузом, который нужен только для теста. Все-равно нужно у себя локально среду настраивать, чтобы работали брейкпойнты и отладка

2021-11-11 16:38 UTC, talyguryn approved these changes

2021-11-11 16:50 UTC, nikmel2803 reviewed
ыыы экспресс js в 21 году, давайте выпилим его нахой

https://dev.to/romainlanz/why-you-should-drop-expressjs-in-2021-711
https://habr.com/ru/post/555668/

давайте лучше https://www.fastify.io

2021-11-11 16:50 UTC, nikmel2803 commented on docker-compose.yml
> +    image: node:14
лучше 16 ставить, 14 уже не активная, а только в режиме поддержки

2021-11-11 16:51 UTC, nikmel2803 commented on src/index.ts
> +const app = express();
в ts же должны работать import. Может лучше их юзать?

2021-11-12 16:29 UTC, talyguryn approved these changes

2021-11-12 17:03 UTC, n0str approved these changes

2021-11-12 17:28 UTC, merged