Added popup with information about task
codex-team/task-manager pull request #97
Opened 2022-01-11 17:20 UTC by slaveeks

resolve #89

2022-01-16 16:28 UTC, TatianaFomina commented on app/frontend/src/components/layouts/popup/TaskPopup.tsx
> +import React, { useEffect, useState } from 'react';
предлагаю перенести этот компонент в директорию `/views/project-view/components`, так как он имеет смысл только в контексте просмотра проекта

2022-01-16 16:28 UTC, TatianaFomina commented on app/frontend/src/custom.d.ts
> +declare module '@editorjs/paragraph';
а этот файл нужен?

2022-01-16 16:28 UTC, TatianaFomina commented on app/frontend/src/services/tasks.ts
> +export async function getTaskById(data: GetTaskByIdMessagePayload): Promise<GetTaskByIdResponsePayload> {
мб стоит в качестве параметра сразу `id` передавать?

2022-01-16 16:28 UTC, TatianaFomina commented on app/types/entities/task.ts
> +  dateCreated: string;
а mongoose схему таска (`app/backend/src/database/models/task.ts`) тоже тогда следует обновить?

2022-01-16 16:28 UTC, TatianaFomina commented on app/frontend/src/components/UI/card/CardLink.tsx
> +import styled from 'styled-components';
этот компонент я б тоже в `/views/project-view/components` перенесла

2022-01-17 11:54 UTC, slaveeks commented on app/frontend/src/custom.d.ts
> +declare module '@editorjs/paragraph';
Ага, для тайпскрипта

2022-01-17 11:55 UTC, slaveeks commented on app/types/entities/task.ts
> +  dateCreated: string;
Вообще, я думаю, не стоит, ибо при создании таски нужно будет еще dateCreated прописывать, а там и так дефолтное значение всегда

2022-01-17 14:19 UTC, neSpecc commented on app/backend/src/ui/methods/task/get-task-by-id.ts
> + * @param [taskId] - task's identifier,
это опциональный параметр?

2022-01-17 14:19 UTC, neSpecc commented on app/frontend/src/components/views/project-view/components/CardLink.tsx
> +      <StyledLink
а почему просто в Card не добавить эту ссылку?

2022-01-17 14:19 UTC, neSpecc commented on app/frontend/src/components/views/project-view/components/TaskPopup.tsx
> +            const editor = new EditorJS({
может для редактора стоит сделать отдельный компонент? Думаю, где-то еще может пригодиться

2022-01-17 16:36 UTC, slaveeks commented on app/frontend/src/components/views/project-view/components/CardLink.tsx
> +      <StyledLink
Просто я тут использую обертку, чтобы useMatch использовать для выделения выбранной карточки

2022-01-17 17:40 UTC, talyguryn approved these changes

2022-01-17 18:53 UTC, TatianaFomina commented on app/types/entities/task.ts
> +  dateCreated: string;
а здесь почему тогда это поле обязательным стало?

2022-01-17 18:55 UTC, TatianaFomina commented on app/frontend/src/custom.d.ts
> +declare module '@editorjs/paragraph';
Вроде @talyguryn говорил, что все нужные типы уже есть, не?

2022-01-17 18:57 UTC, slaveeks commented on app/types/entities/task.ts
> +  dateCreated: string;
Ну так как оно при создании таски всегда создаётся по дефолту, его не может не быть, когда запрашиваешь

2022-01-17 19:44 UTC, slaveeks commented on app/frontend/src/custom.d.ts
> +declare module '@editorjs/paragraph';
Не, мы этот момент обсуждали

2022-01-17 19:55 UTC, slaveeks commented on app/types/entities/task.ts
> +  dateCreated: string;
Ну если я не ошибаюсь, если в модели поставить required, то в этом случае обязательно самостоятельно вносить дату при создании документа и значение до дефолту не будет иметь смысла

2022-01-18 18:26 UTC, gohabereg requested changes

2022-01-18 18:26 UTC, gohabereg commented on app/backend/src/ui/transport-server/controller.ts
> +    case 'get-task-by-id': return {
Нужно бы эти значения типизировать, литералом или лучше через Enum

2022-01-18 18:26 UTC, gohabereg commented on app/frontend/src/components/UI/card/Card.tsx
> +export interface Props{
Надо eslint прогнать

2022-01-18 18:26 UTC, gohabereg commented on app/frontend/src/components/views/project-view/components/TaskPopup.tsx
> +const TaskPopup: React.FC<Props> = (props) => {
Если пропсы не нужны, лучше убрать переменную

2022-01-18 18:26 UTC, gohabereg commented on app/frontend/src/components/views/project-view/components/TaskPopup.tsx
> +      getTaskById( id )
Для асинхронных эффектов можно такой хак использовать, чтобы не было коллбеков

```
useEffect(() => {
  const exec = async () => {
    const response = await asyncFunction();

    ...
  };

  exec();
}, []);
```

2022-01-18 18:26 UTC, gohabereg commented on app/frontend/src/components/views/project-view/components/TaskPopup.tsx
> +    if (task) {
Тут тоже можно if перевернуть

2022-01-18 18:26 UTC, gohabereg commented on app/frontend/src/components/views/project-view/components/TaskPopup.tsx
> +    <PopupWrapper backDropClick={onClose} isPopupVisible={true} { ...props }>
Очень большой компонент, рекомендую разбить на несколько, например TaskContent и TaskInfo

2022-01-18 18:26 UTC, gohabereg commented on app/frontend/src/components/views/project-view/components/TaskPopup.tsx
> +            <Editor data={data} tools={{ header: Header,
Имхо, тулзы лучше внутри Editor определять, а не передавать пропсами

2022-01-18 18:26 UTC, gohabereg commented on app/frontend/src/components/views/project-view/components/TaskPopup.tsx
> +          { projectTitle ?
И кажется можно объединить с такой же штукой выше

2022-01-18 18:26 UTC, gohabereg commented on app/frontend/src/components/views/project-view/components/TaskPopup.tsx
> +const formatDate = (dateToFormat: string): string => {
Лучше вынести в отдельный файл

2022-01-20 18:08 UTC, slaveeks commented on app/backend/src/ui/transport-server/controller.ts
> +    case 'get-task-by-id': return {
Этим сейчас Виталик занимается, там есть реквест с рефакторингом бэкенда

2022-01-20 18:09 UTC, slaveeks commented on app/frontend/src/components/views/project-view/components/TaskPopup.tsx
> +            <Editor data={data} tools={{ header: Header,
Вообще, это библиотека с компонентом для эдитора, создал файлик tools, чтобы их использовать было проще

2022-01-20 18:12 UTC, TatianaFomina commented on app/frontend/src/components/views/project-view/components/TaskInfo.tsx
> +  console.log('Changed');
это можно убрать?

2022-01-20 18:13 UTC, slaveeks commented on app/frontend/src/components/views/project-view/components/TaskInfo.tsx
> +  console.log('Changed');
У Селеста нужна какая-то функция как параметр, решил пока так сделать

2022-01-21 09:34 UTC, neSpecc commented on app/frontend/src/components/views/project-view/components/CardLink.tsx
> +      <StyledLink
сорри, все равно не понимаю, зачем создавать компонент `CardLink`

2022-01-21 10:44 UTC, slaveeks commented on app/frontend/src/components/views/project-view/components/CardLink.tsx
> +      <StyledLink
Ну эта обертка позволяет определить, соответствует ли текущий роут карточке.

2022-01-21 10:49 UTC, slaveeks commented on app/frontend/src/components/views/project-view/components/CardLink.tsx
> +      <StyledLink
Я сделал аналогично projectLink, у них похожая механика

2022-01-21 18:05 UTC, gohabereg commented on app/frontend/src/components/views/project-view/components/CardLink.tsx
> +      <StyledLink
Если аналогичный код, то можно это сделать HOC. Отдельно от реквеста, конечно

2022-01-21 18:13 UTC, gohabereg approved these changes

2022-01-21 18:13 UTC, gohabereg commented on app/frontend/src/components/views/project-view/ProjectView.tsx
> +        </Route>
Лишний закрывающий тег

2022-01-21 18:13 UTC, gohabereg commented on app/frontend/src/components/views/project-view/components/TaskContent.tsx
> +        <Editor data={data} tools={EDITOR_JS_TOOLS}/> }
Все равно не очень понятно, зачем тулзы передавать как пропсы, если можно их внутри компонента Editor инкапсулировать

2022-01-21 18:13 UTC, gohabereg commented on app/frontend/src/components/views/project-view/components/TaskPopup.tsx
> +    exec().then();
```suggestion
    exec();
```

2022-01-21 18:13 UTC, gohabereg commented on app/frontend/src/components/views/project-view/components/TaskPopup.tsx
> +    const exec = async ():Promise<void> => {
```suggestion

    const exec = async ():Promise<void> => {
```

2022-01-21 18:13 UTC, gohabereg commented on app/frontend/src/components/views/project-view/components/TaskPopup.tsx
> +      if (!response.task) {
```suggestion

      if (!response.task) {
```

2022-01-21 18:13 UTC, gohabereg commented on app/frontend/src/components/views/project-view/components/TaskPopup.tsx
> +      const blocks: OutputData = { blocks: JSON.parse(response.task.text).blocks };
```suggestion

      const blocks: OutputData = { blocks: JSON.parse(response.task.text).blocks };
```

2022-01-21 18:13 UTC, gohabereg commented on app/frontend/src/components/views/project-view/components/TaskPopup.tsx
> +    const projectId = task.projectId;
```suggestion

    const projectId = task.projectId;
```

2022-01-24 18:09 UTC, merged